#
# ASM    flags
#
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -D__STARTUP_CLEAR_BSS")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -D__STARTUP_INITIALIZE_NONCACHEDATA")

string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -Os")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -mthumb")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -mcpu=cortex-m7")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -mapcs")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -mfloat-abi=hard")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -mfpu=fpv5-d16")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -fdata-sections")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -ffreestanding")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -ffunction-sections")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -fno-builtin")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -fno-common")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -std=gnu99")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -Wall")

if (OPENVG_DBG_INFO)
	string(APPEND CMAKE_ASM_FLAGS_SDRAM_RELEASE " -g")
endif()


#
# C    flags
#
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -DUSE_SDRAM")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -DCPU_MIMXRT1176DVMAA_cm7")
if (MCU_SDK_VER STREQUAL "2.15.x")
	string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DSDK_OS_FREE_RTOS")
else()
	string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DFSL_RTOS_FREE_RTOS")
endif()
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -D__FREERTOS__=1")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -DCPU_MIMXRT1176AVM8A_cm7=1")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -DSTATIC_LINK=1")

string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -fdiagnostics-color")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -Os")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -mthumb")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -mcpu=cortex-m7")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -mapcs")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -mfloat-abi=hard")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -mfpu=fpv5-d16")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -Wall")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -fno-common")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -ffunction-sections")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -fdata-sections")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -ffreestanding")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -fno-builtin")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -std=gnu99")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -MMD")
string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -MP")

if (OPENVG_DBG_INFO)
	string(APPEND CMAKE_C_FLAGS_SDRAM_RELEASE " -g")
endif()

