#
# ASM    flags
#
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -D__STARTUP_CLEAR_BSS")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -D__STARTUP_INITIALIZE_NONCACHEDATA")

string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -O0")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -mthumb")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -mcpu=cortex-m7")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -mapcs")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -mfloat-abi=hard")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -mfpu=fpv5-d16")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -fdata-sections")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -ffreestanding")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -ffunction-sections")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -fno-builtin")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -fno-common")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -std=gnu99")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -Wall")

string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -DDBG")
string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -DDEBUG")

if (OPENVG_DBG_INFO)
	string(APPEND CMAKE_ASM_FLAGS_SDRAM_DEBUG " -g")
endif()


#
# C    flags
#
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DDBG=1")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DDEBUG=1")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DUSE_SDRAM")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DCPU_MIMXRT1176DVMAA_cm7")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DSDK_OS_FREE_RTOS")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DCPU_MIMXRT1176AVM8A_cm7=1")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -DSTATIC_LINK=1")

string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -fdiagnostics-color")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -O0")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -mthumb")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -mcpu=cortex-m7")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -mapcs")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -mfloat-abi=hard")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -mfpu=fpv5-d16")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -Wall")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -fno-common")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -ffunction-sections")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -fdata-sections")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -ffreestanding")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -fno-builtin")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -std=gnu99")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -MMD")
string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -MP")

if (OPENVG_DBG_INFO)
	string(APPEND CMAKE_C_FLAGS_SDRAM_DEBUG " -g")
endif()

